const products = [
    {
        id:0,
        name:`PowerColor RX 6600 XT Fighter 8GB GDDR6 FreeSync`,
        description: "Karta graficzna umożliwiająca granie w rozdzielczości Full HD",
        category: "Karty Graficzne",
        photo:"./photo/fighter6600xt.png",
        alt:"Karta Graficzna PowerColor RX 6600 XT Fighter 8GB GDDR6 FreeSync",
        price: 2500,
        sale: 1,
        saleAmount: 300,
        quantity: 1,
    },
    {
        id:1,
        name:"Sapphire Pulse Radeon RX 6800 Gaming OC 16GB GDDR6",
        description: "Karta graficzna umożliwiająca granie w rozdzielczości 4K",
        category: "Karty Graficzne",
        photo:"./photo/rx6800.png",
        alt:" Karta Graficzna Sapphire Pulse Radeon RX 6800 Gaming OC 16GB GDDR6",
        price: 3900,
        quantity: 1,
    },
    {
        id:2,
        name:"Płyta główna Gigabyte B660M DS3H DDR4",
        description: "Jedna z nalepszych płyt głównych ostatnich lat.",
        category: "Płyta Główna",
        photo:"./photo/B660.png",
        alt:"Płyta główna Gigabyte B660M DS3H DDR4",
        price: 550,
        quantity: 1,
    },
    {
        id:3,
        name:"Procesor Intel Core i5-11400F, 2.6 GHz, 12 MB, BOX",
        description: "Taktowanie 4,4GHz, 6 rdzeni i 12 wątków",
        category: "Procesor",
        photo:"./photo/inteli5.png",
        alt:"Procesor Intel Core i5-11400F, 2.6 GHz, 12 MB, BOX",
        price: 750,
        sale: 1,
        saleAmount: 50,
        quantity: 1,
    },
    {
        id:4,
        name:"Procesor Intel Core i7-11400F, 2.6 GHz, 12 MB, BOX",
        description: "Taktowanie 5GHz, 8 rdzeni i 16 wątków",
        category: "Procesor",
        photo:"./photo/inteli7.png",
        alt:"Procesor Intel Core i7-11400F, 2.6 GHz, 12 MB, BOX",
        price: 1150,
        sale: 1,
        saleAmount: 50,
        quantity: 1,
    },
    {
        id:5,
        name:"Pamięć GoodRam DDR4 16 GB",
        description: "2400MHz, CL15",
        category: "Pamięć RAM",
        photo:"./photo/ram.jpg",
        alt:"Pamięć GoodRam DDR4 16 GB",
        price: 250,
        sale: 1,
        saleAmount: 20,
        quantity: 1,
    },
    {
        id:6,
        name:"Dysk SSD Crucial 480GB",
        description: "2.5''",
        category: "Dyski",
        photo:"./photo/ssd.jpg",
        alt:"Dysk SSD Crucial 480GB",
        price: 150,
        quantity: 1,
    }
    ]
    