const products = [
{
    id:0,
    name:`PowerColor RX 6600 XT Fighter 8GB GDDR6 FreeSync`,
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque amet, culpa blanditiis rem cupiditate voluptatibus porro sapiente, facilis harum eveniet repellendus accusamus architecto iusto cumque quibusdam? Vitae totam vel nam.",
    category: "Karty Graficzne",
    photo:"./photo/fighter6600xt.png",
    alt:" opis fonetyczny",
    price: 2500,
    sale: 1,
    saleAmount: 300.01,
},
{
    id:1,
    name:"Sapphire Pulse Radeon RX 6800 Gaming OC 16GB GDDR6",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque amet, culpa blanditiis rem cupiditate voluptatibus porro sapiente, facilis harum eveniet repellendus accusamus architecto iusto cumque quibusdam? Vitae totam vel nam.",
    category: "Karty Graficzne",
    photo:"./photo/rx6800.png",
    alt:" opis fonetyczny",
    price: 3900.99,
},
{
    id:2,
    name:"Płyta główna Gigabyte B660M DS3H DDR4",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque amet, culpa blanditiis rem cupiditate voluptatibus porro sapiente, facilis harum eveniet repellendus accusamus architecto iusto cumque quibusdam? Vitae totam vel nam.",
    category: "Płyta Główna",
    photo:"./photo/B660.png",
    alt:" opis fonetyczny",
    price: 550,
},
{
    id:3,
    name:"Procesor Intel Core i5-11400F, 2.6 GHz, 12 MB, BOX",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque amet, culpa blanditiis rem cupiditate voluptatibus porro sapiente, facilis harum eveniet repellendus accusamus architecto iusto cumque quibusdam? Vitae totam vel nam.",
    category: "Procesor",
    photo:"./photo/inteli5.png",
    alt:" opis fonetyczny",
    price: 750,
    sale: 1,
    saleAmount: 50,
}
]
